### ISSUE TITLE
[FEATURE] Weapon/Armor Levelling System

### ISSUE THREAD

**Issue by pokesmells** [PlayerEXDirectorsCut/playerex#23]
**Weapon and Armor Leveling** will provide XP based on mob kills, with different XP amounts for different types of mobs.

- **XP Distribution:** Passive mobs grant 10 XP, and bosses grant `50 XP`. This base XP can be adjusted based on the mob's level. For instance, a level 48 passive mob could have its XP multiplied accordingly.

- **Weapon Leveling:** Each weapon level increases damage by `0.1`.

- **Armor Leveling:** Each armor level increases armor by `0.1` and boosts damage reduction based on a predefined maximum. For example, if the config sets a maximum damage reduction of `75%` and each level grants 1% reduction, you would reach the max reduction well before hitting `500 levels`. Beyond that, damage reduction would cap at `75%`, but armor would continue to increase, reaching +50 armor at level 500.

**TODO**

- [x] Make XP goals from mobs as described above and add XP scaling for each level on both armor and weapons.
- [x] Specify what each level gives to both armor and weapons EX. Each level gives 0.1 attack damage to weapons and 0.1 armor and a percentage of damage reduction to armor.
- [x] Add configs to allow users to specify how much each mob type gives in terms of XP, how much armor and damage reduction each level gives, how much attack damage each level gives, what the max level should be, and the level scaling like the amount of XP between each level, and to turn off the feature.
- [x] Make it so weapons in the wild have random weapon levels, and so does armor. Make it a range of levels per specified dimension. EX. Overworld Range 1-50, Nether Range 70-90, etc

**Comment by RedstoneWizard08** [comment]
I will work on this :D

**Comment by RedstoneWizard08** [comment]
MY TODO LIST

- [ ] Make XP goals from mobs as described above and add XP scaling for each level on both armor and weapons.
- [ ] Specify what each level gives to both armor and weapons EX. Each level gives 0.1 attack damage to weapons and 0.1 armor and a percentage of damage reduction to armor.
- [ ] Add configs to allow users to specify how much each mob type gives in terms of XP, how much armor and damage reduction each level gives, how much attack damage each level gives, what the max level should be, and the level scaling like the amount of XP between each level, and to turn off the feature.
- [ ] Make it so weapons in the wild have random weapon levels, and so does armor. Make it a range of levels per specified dimension. EX. Overworld Range 1-50, Nether Range 70-90, etc
- [ ] Make it compatible with Simple Discord RPC to show weapon/armor levels on the RPC
